### ISSUE TITLE
classify severity of various network attacks

### ISSUE THREAD

**Issue by IsaiahHarvi** [IsaiahHarvi/NIDS#66]

**Comment by ksantschi02** [comment]
Ranking of network attacks from least to most critical:

1. PortScan - Typically just reconnaissance used to identify open ports/services. Does not cause harm on its own, but can be a precursor to more dangerous attacks
2. FTP-Patator - Brute force targeting FTP authentication. Limited to attacking a specific service and relies on weak security
3. SSH-Patator - Similar to FTP-Patator but targets SSH authentication, which generally protects critical access points. Still relies on a weak security system
4. DoS Slowloris - Exhausts server resources by maintaining connections. Limited to a single target and is easily mitigated
5. DoS Slowhttptest - Similar to Slowloris, but can target various servers simultaneously
6. DoS GoldenEye - Similar to previous 2 DoS attacks, more aggressive
7. DoS Hulk - Similar to GoldenEye, but far more aggressive and designed to flood web servers in a moment
8. DDoS - More severe than the simpler forms of DoS attacks because it involves traffic from multiple sources, making it harder to mitigate
9. Bot - Compromises systems which can then be used to coordinate automated network attacks such as DDoS and spreading malware. Can lead to large-scale consequences
10. Heartbleed - Vulnerability in the OpenSSL library. Allows attackers to read sensitive data from server memory, such as private keys and user info
11. Infiltration - Unauthorized access and control over systems within a network. May lead to mass data theft and further network compromise

1-3: Low severity
4-7: Medium severity
8-11: High severity
